// Example actions
export const USERS_PENDING = 'USERS_PENDING';
export const USERS_FULFILLED = 'USERS_FULFILLED';
export const USERS_REJECTED = 'USERS_REJECTED';

export const SESSION_PENDING = 'SESSION_PENDING';
export const SESSION_FULFILLED = 'SESSION_FULFILLED';
export const SESSION_REJECTED = ' SESSION_REJECTED';

export const AUTH_PENDING = 'AUTH_PENDING';
export const AUTH_FULFILLED = 'AUTH_FULFILLED';
export const AUTH_REJECTED = ' AUTH_REJECTED';