// Example actions
export const USERS_PENDING = 'USERS_PENDING';
export const USERS_FULFILLED = 'USERS_FULFILLED';
export const USERS_REJECTED = 'USERS_REJECTED';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
